/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: src/sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  formattedTitle?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug: Slug;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: PageBuilder;
  excerpt?: string;
  location: "Beirut" | "Dubai" | "Abu Dhabi" | "Cairo" | "Doha" | "Riyadh";
  categories: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  year: number;
  featured?: boolean;
  overlayTextColor?: "white" | "dark";
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & HeroBlock)
  | ({
      _key: string;
    } & ImageDetailsBlock)
  | ({
      _key: string;
    } & ImageBlock)
  | ({
      _key: string;
    } & CenteredTextBlock)
  | ({
      _key: string;
    } & ImagePairBlock)
  | ({
      _key: string;
    } & MixedImagePairBlock)
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type CenteredTextBlock = {
  _type: "centeredTextBlock";
  title?: string;
  description: string;
  width: "full" | "twoThirds" | "half";
};

export type MixedImagePairBlock = {
  _type: "mixedImagePairBlock";
  landscapeImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  landscapeAlt: string;
  nonLandscapeImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  nonLandscapeAlt: string;
  nonLandscapeFormat: "square" | "portrait";
  landscapePosition: "left" | "right";
};

export type ImagePairBlock = {
  _type: "imagePairBlock";
  leftImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  leftAlt: string;
  rightImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  rightAlt: string;
};

export type ImageBlock = {
  _type: "imageBlock";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
  variant: "fullLandscape" | "compactLandscape" | "halfSquare";
};

export type ImageDetailsBlock = {
  _type: "imageDetailsBlock";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageAlt: string;
  title?: string;
  subtitle?: string;
  description: string;
  layout: "imageRight" | "imageLeft";
  imageFormat: "square" | "portrait" | "landscape";
};

export type HeroBlock = {
  _type: "heroBlock";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  color?: Color;
  slug: Slug;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | CategoryReference
  | Project
  | PageBuilder
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | CenteredTextBlock
  | MixedImagePairBlock
  | ImagePairBlock
  | ImageBlock
  | ImageDetailsBlock
  | HeroBlock
  | Category
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/lib/queries.ts
// Variable: FEATURED_PROJECT_QUERY
// Query: *[_type == "project" && featured == true] | order(_createdAt desc) [0] {      _id,  title,  formattedTitle,  slug,  coverImage,  excerpt,  "location": coalesce(location, category),  categories[]->{    _id,    title,    "slug": slug.current,    "color": color.hex  },  year,  featured,  overlayTextColor  }
export type FEATURED_PROJECT_QUERY_RESULT = {
  _id: string;
  title: string;
  formattedTitle: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: Slug;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt: string | null;
  location: "Abu Dhabi" | "Beirut" | "Cairo" | "Doha" | "Dubai" | "Riyadh";
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    color: string | null;
  }>;
  year: number;
  featured: true;
  overlayTextColor: "dark" | "white" | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_PROJECTS_QUERY
// Query: *[_type == "project"] | order(_createdAt desc) {      _id,  title,  formattedTitle,  slug,  coverImage,  excerpt,  "location": coalesce(location, category),  categories[]->{    _id,    title,    "slug": slug.current,    "color": color.hex  },  year,  featured,  overlayTextColor  }
export type ALL_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  formattedTitle: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: Slug;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt: string | null;
  location: "Abu Dhabi" | "Beirut" | "Cairo" | "Doha" | "Dubai" | "Riyadh";
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    color: string | null;
  }>;
  year: number;
  featured: boolean | null;
  overlayTextColor: "dark" | "white" | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true] | order(_createdAt desc) {      _id,  title,  formattedTitle,  slug,  coverImage,  excerpt,  "location": coalesce(location, category),  categories[]->{    _id,    title,    "slug": slug.current,    "color": color.hex  },  year,  featured,  overlayTextColor  }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  formattedTitle: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: Slug;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt: string | null;
  location: "Abu Dhabi" | "Beirut" | "Cairo" | "Doha" | "Dubai" | "Riyadh";
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    color: string | null;
  }>;
  year: number;
  featured: true;
  overlayTextColor: "dark" | "white" | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_PAGE_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{        _id,  title,  formattedTitle,  slug,  coverImage,  excerpt,  "location": coalesce(location, category),  categories[]->{    _id,    title,    "slug": slug.current,    "color": color.hex  },  year,  featured,  overlayTextColor,    content[]{    ...,    _type == "heroBlock" => {      _key,      _type,      image,      alt    },    _type == "imageDetailsBlock" => {      _key,      _type,      image,      imageAlt,      title,      subtitle,      description,      layout,      imageFormat    },    _type == "imageBlock" => {      _key,      _type,      image,      alt,      variant    },    _type == "centeredTextBlock" => {      _key,      _type,      title,      description,      width    },    _type == "imagePairBlock" => {      _key,      _type,      leftImage,      leftAlt,      rightImage,      rightAlt    },    _type == "mixedImagePairBlock" => {      _key,      _type,      landscapeImage,      landscapeAlt,      nonLandscapeImage,      nonLandscapeAlt,      nonLandscapeFormat,      landscapePosition    }  }  }
export type PROJECT_PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  formattedTitle: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: Slug;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt: string | null;
  location: "Abu Dhabi" | "Beirut" | "Cairo" | "Doha" | "Dubai" | "Riyadh";
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    color: string | null;
  }>;
  year: number;
  featured: boolean | null;
  overlayTextColor: "dark" | "white" | null;
  content: Array<
    | {
        _key: string;
        _type: "centeredTextBlock";
        title: string | null;
        description: string;
        width: "full" | "half" | "twoThirds";
      }
    | {
        _key: string;
        _type: "heroBlock";
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string;
      }
    | {
        _key: string;
        _type: "imageBlock";
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string;
        variant: "compactLandscape" | "fullLandscape" | "halfSquare";
      }
    | {
        _key: string;
        _type: "imageDetailsBlock";
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        imageAlt: string;
        title: string | null;
        subtitle: string | null;
        description: string;
        layout: "imageLeft" | "imageRight";
        imageFormat: "landscape" | "portrait" | "square";
      }
    | {
        _key: string;
        _type: "imagePairBlock";
        leftImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        leftAlt: string;
        rightImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        rightAlt: string;
      }
    | {
        _key: string;
        _type: "mixedImagePairBlock";
        landscapeImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        landscapeAlt: string;
        nonLandscapeImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        nonLandscapeAlt: string;
        nonLandscapeFormat: "portrait" | "square";
        landscapePosition: "left" | "right";
      }
  > | null;
} | null;
