/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: src/sanity/extract.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandLine?: string;
  secondaryNav?: Array<{
    label: string;
    href: string;
    _key: string;
  }>;
  locations?: Array<{
    label: string;
    address?: string;
    _key: string;
  }>;
  phone?: string;
  email?: string;
  mapUrl?: string;
  socials?: Array<{
    platform: "instagram" | "linkedin";
    url: string;
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PublicationsPage = {
  _id: string;
  _type: "publicationsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  publications?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    publication: string;
    date?: string;
    description?: string;
    url?: string;
    linkLabel?: string;
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type JoinUsPage = {
  _id: string;
  _type: "joinUsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heading?: string;
  body?: string;
  email?: string;
};

export type StudioPage = {
  _id: string;
  _type: "studioPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  founder?: {
    name?: string;
    role?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    bio?: string;
    linkLabel?: string;
    linkUrl?: string;
  };
  intro?: {
    heading?: string;
    body?: string;
  };
  disciplines?: {
    heading?: string;
    body?: string;
    sectors?: Array<string>;
    services?: Array<string>;
  };
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  location: string;
  year?: string;
  status?: "In progress" | "On hold" | "Completed";
  category: CategoryReference;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  credits?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  orderRank?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImageAssetReference
  | PublicationsPage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityFileAssetReference
  | JoinUsPage
  | StudioPage
  | CategoryReference
  | Project
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/lib/queries.ts
// Variable: ARCHIVE_PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current) && count(images) > 0      && ($category == null || category->slug.current == $category)]    | order(orderRank) {    _id,    title,    "slug": slug.current,    location,    status,    year,    "category": category->title,    "thumb": images[0]{      alt,      asset,      hotspot,      crop,      "lqip": asset->metadata.lqip,      "dimensions": asset->metadata.dimensions{ width, height, aspectRatio }    }  }
export type ARCHIVE_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  location: string;
  status: "Completed" | "In progress" | "On hold" | null;
  year: string | null;
  category: string;
  thumb: {
    alt: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    lqip: string | null;
    dimensions: {
      width: number;
      height: number;
      aspectRatio: number;
    } | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)      && count(*[_type == "project" && references(^._id) && count(images) > 0]) > 0]    | order(title asc) {    _id,    title,    "slug": slug.current  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: VIEWER_PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current) && count(images) > 0      && ($category == null || category->slug.current == $category)]    | order(orderRank) {   _id,  title,  "slug": slug.current,  location,  year,  images[]{    _key,    alt,    asset,    hotspot,    crop,    "lqip": asset->metadata.lqip,    "dimensions": asset->metadata.dimensions{ width, height, aspectRatio }  } }
export type VIEWER_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  location: string;
  year: string | null;
  images: Array<{
    _key: string;
    alt: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    lqip: string | null;
    dimensions: {
      width: number;
      height: number;
      aspectRatio: number;
    } | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_DETAIL_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  location,  year,  images[]{    _key,    alt,    asset,    hotspot,    crop,    "lqip": asset->metadata.lqip,    "dimensions": asset->metadata.dimensions{ width, height, aspectRatio }  },    description,    credits  }
export type PROJECT_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  location: string;
  year: string | null;
  images: Array<{
    _key: string;
    alt: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    lqip: string | null;
    dimensions: {
      width: number;
      height: number;
      aspectRatio: number;
    } | null;
  }> | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  credits: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    brandLine,    secondaryNav[]{ label, href },    locations[]{ label, address },    phone,    email,    mapUrl,    socials[]{ platform, url }  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      brandLine: null;
      secondaryNav: null;
      locations: null;
      phone: null;
      email: null;
      mapUrl: null;
      socials: null;
    }
  | {
      brandLine: null;
      secondaryNav: null;
      locations: null;
      phone: null;
      email: string | null;
      mapUrl: null;
      socials: null;
    }
  | {
      brandLine: string | null;
      secondaryNav: Array<{
        label: string;
        href: string;
      }> | null;
      locations: Array<{
        label: string;
        address: string | null;
      }> | null;
      phone: string | null;
      email: string | null;
      mapUrl: string | null;
      socials: Array<{
        platform: "instagram" | "linkedin";
        url: string;
      }> | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: STUDIO_PAGE_QUERY
// Query: *[_id == "studioPage"][0]{    founder{ name, role, bio, linkLabel, linkUrl, image{  asset,  hotspot,  crop,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions{ width, height, aspectRatio }} },    intro{ heading, body },    disciplines{ heading, body, sectors, services }  }
export type STUDIO_PAGE_QUERY_RESULT =
  | {
      founder: null;
      intro: null;
      disciplines: null;
    }
  | {
      founder: {
        name: string | null;
        role: string | null;
        bio: string | null;
        linkLabel: string | null;
        linkUrl: string | null;
        image: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      intro: {
        heading: string | null;
        body: string | null;
      } | null;
      disciplines: {
        heading: string | null;
        body: string | null;
        sectors: Array<string> | null;
        services: Array<string> | null;
      } | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: PUBLICATIONS_PAGE_QUERY
// Query: *[_id == "publicationsPage"][0]{    publications[]{      _key,      publication,      date,      description,      url,      linkLabel,      image{  asset,  hotspot,  crop,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions{ width, height, aspectRatio }}    }  }
export type PUBLICATIONS_PAGE_QUERY_RESULT =
  | {
      publications: null;
    }
  | {
      publications: Array<{
        _key: string;
        publication: string;
        date: string | null;
        description: string | null;
        url: string | null;
        linkLabel: string | null;
        image: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      }> | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: JOIN_US_PAGE_QUERY
// Query: *[_id == "joinUsPage"][0]{    "videoUrl": video.asset->url,    image{  asset,  hotspot,  crop,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions{ width, height, aspectRatio }},    heading,    body,    email  }
export type JOIN_US_PAGE_QUERY_RESULT =
  | {
      videoUrl: null;
      image: null;
      heading: null;
      body: null;
      email: null;
    }
  | {
      videoUrl: null;
      image: null;
      heading: null;
      body: null;
      email: string | null;
    }
  | {
      videoUrl: string | null;
      image: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
      heading: string | null;
      body: string | null;
      email: string | null;
    }
  | null;
